// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT65HJ5WsUg_6X01R5FAUzuJe5jU-oIFU',
    appId: '1:956242711124:web:024ed6fa70df5b493953c1',
    messagingSenderId: '956242711124',
    projectId: 'hayagsync',
    authDomain: 'hayagsync.firebaseapp.com',
    storageBucket: 'hayagsync.firebasestorage.app',
    measurementId: 'G-3G6B9XL2XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-C4myxERTUM2SRYqLGtn9GMd08KWSEYg',
    appId: '1:956242711124:android:98760e43704c8ce13953c1',
    messagingSenderId: '956242711124',
    projectId: 'hayagsync',
    storageBucket: 'hayagsync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrIIljo4S7jaLvxYXvJNE4OAdrGElZai4',
    appId: '1:956242711124:ios:d14b34446d1194603953c1',
    messagingSenderId: '956242711124',
    projectId: 'hayagsync',
    storageBucket: 'hayagsync.firebasestorage.app',
    iosBundleId: 'com.example.hayagsyncApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrIIljo4S7jaLvxYXvJNE4OAdrGElZai4',
    appId: '1:956242711124:ios:d14b34446d1194603953c1',
    messagingSenderId: '956242711124',
    projectId: 'hayagsync',
    storageBucket: 'hayagsync.firebasestorage.app',
    iosBundleId: 'com.example.hayagsyncApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT65HJ5WsUg_6X01R5FAUzuJe5jU-oIFU',
    appId: '1:956242711124:web:5f8a5dfadb8066243953c1',
    messagingSenderId: '956242711124',
    projectId: 'hayagsync',
    authDomain: 'hayagsync.firebaseapp.com',
    storageBucket: 'hayagsync.firebasestorage.app',
    measurementId: 'G-WX0E65W66E',
  );
}
